# Generated by Django 4.1.2 on 2022-11-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'linea pedido', 'verbose_name_plural': 'lineas pedidos'},
        ),
    ]
